### ISSUE TITLE
maybe there is a source?

### ISSUE THREAD

**Issue by zoomx** [tardate/LittleArduinoProjects#1]
Hello,
here
[http://www.instructables.com/id/How-to-make-a-digital-clock-kit-based-on-Atmel/](url)
(Copy and paste links)
an almost identical kit is described, it seems only mirrored.
your kit is this [one](https://github.com/tardate/LittleArduinoProjects/tree/master/Electronics101/ElectronicClockKit)

There is also a C source but I don't know if it works or not.

**Comment by tardate** [comment]
@zoomx nice find! Thanks for the tip - I've updated my notes. Still have to try the code .. looks about what I'd expect though
