### ISSUE TITLE
request

### ISSUE THREAD

**Issue by Aryshshar** [tardate/LittleArduinoProjects#13]
Hi engineer
Is it possible to email the circuit diagram with the simulator format used for servant
I'm going to do a simulation by changing the values of the elements
thank you
![core_schematic](https://user-images.githubusercontent.com/51678665/65151263-fd0da900-da3a-11e9-89c2-697a83c70bfa.jpg)

**Comment by tardate** [comment]
@Aryshshar that is from https://github.com/tardate/LittleArduinoProjects/tree/master/Equipment/AdjustablePowerSupplyKit I think? Sorry, no, that's one project I haven't captured the schematic for - just have the picture
