### ISSUE TITLE
AudioEffectsChips/H83A - Song names

### ISSUE THREAD

**Issue by whc2001** [tardate/LittleArduinoProjects#15]
Here are all the names of the songs in this chip in order (all of them are Chinese pop/folk songs):

||
|-|
| 常回家看看 |
| 有一个姑娘 |
| 心太软 |
| 妈妈的吻 |
| 爱拼才会赢 |
| 月亮惹的祸 |
| 健康歌 |
| 涛声依旧 |
| 拨浪鼓 |
| 好日子 |
| 读书郎 |
| 懂你 |

I also did [a demonstration of this chip (YouTube link)](https://www.youtube.com/watch?v=CIWCA4LYstM) a while ago. Seems like the unstable pitch is due to the breadboard which doesn't make a solid connection for Rosc.

**Comment by tardate** [comment]
Fantastic, thanks @whc2001. I've updated in the notes, including a link to your video - hope you don't mind.

You are right, I had really dodgy breadboard connections that day. Which probably didn't help recognising any of the tunes! Not even 心太软, which I remember singing in 汉语课 many years ago;-)
