### ISSUE TITLE
LEAP#295 schematic correction (crystal tester)

### ISSUE THREAD

**Issue by Ho-Ro** [tardate/LittleArduinoProjects#17]
Hello Paul,

In your schematic of the frequency counter (LEAP#295) a connection dot is missing in the crystal tester part between the emitter and the two capacitors C2/C3.

![image](https://user-images.githubusercontent.com/12542359/90505292-a4ff8b00-e152-11ea-94fd-b13130f776e1.png)

Actual it should look like [this picture](https://www.elprocus.com/wp-content/uploads/2016/04/colpitts-crystal-oscillator.jpg).

Martin

**Comment by tardate** [comment]
cheers @Ho-Ro, thanks for the tip!
