### ISSUE TITLE
LM393 is not an opamp (LineFollowerKit)

### ISSUE THREAD

**Issue by steveschnepp** [tardate/LittleArduinoProjects#26]
Here comes the pedantic police, but the LM393 is not an opamp. It is a comparator. The LM358 would be your usual opamp.

I'm sure you know the difference, but I'm still opening the issue as your site has an awesome learning value. And the "why my LM393 opamp doesn't work?" is a typical question from beginners. The schematics and the pinout being the same.

Funnily, in that circuit, both are working thanks to the PNP transistor driver.

**Comment by tardate** [comment]
thanks @steveschnepp well spotted!.

Fixed that up. Looks like I wasn't paying attention and started writing LM358 when in fact the kit actually uses the LM393
