### ISSUE TITLE
[CD4001/LogicProbe] Improvement using CD4069UB 

### ISSUE THREAD

**Issue by steveschnepp** [tardate/LittleArduinoProjects#29]
Looking at the schematics, it looks like a lot of NOR gates are used in a NOT mode.

In order to be more efficient, let's use a CD4069UB (6xNOT, unbuffered). I have a box of those, and I'm really loving their simplicity. Also the 2 remaining NOT gates could be used as a poor man's clock generator, in order to be able to self-debug the LogicProbe 😉.

To "transform" a CD4069UB into a NOR gate, one just need to add some incoming diodes, which gives us [the following schematics](https://www.falstad.com/circuit/circuitjs.html?ctz=CQAgjCAMB0l5AWAnC1b0DZzQExgBw7IDMSGkA7JMQhcSAlgKwhOSsCmAtGGAFAB3VhSw4KOEBiIgxEyHzBTJ0sEglSEM8TJAATDgDMAhgFcANgBcuZjrvBQHMSP0Xrps5ZuI52E-cfMrGzt2CHYnfgAnT3A1GLAcfAcweD5ojRBvdgzifE1Q1KEMhKSEb3BEqD4AcxjczQyEOEc+ACUGcpKOiXxwhybWRyhoJjaGMi0JBAQkj18ZXxGZJfCRwRAqLwwklMgk4m2qgGMQXt9tPNntUNh4O-u4MG4KbEVGJCYEHCZ8DGICGjDe5RU4zSagnaVAr3BRKXg+GQqBLnCR+QymSzWWz2MJA-hCXZXCSEzKHeRFFSVcShKHrakVJKXBlVIRMcgyNmsdlzdZslFc3z4JLkgXgpgicEipgJGQDaWo668mUeeWZRAs1jK7TIUSK9p8xGaA2qOT9dgsPowUa1A1ZUXEA4tAya1Fy7kDB3YC2wHB8Z2q4jq23qzorH1+jaOwOaCh5NVeYlhyC+510UQDWOaIjsT1gJO+2qZzIIosOrDhMZFnDSIsmoZyoZWumOjybSXN9PsNPtoRVi7NHm9uOt4dCjVVzl9uQRpDTeMgFASaPFr1AlMLufZhdxLe5-M1bdLhGLzKOivtE-VzQnut9BuWtZCWdZi4TQcbl8SZ-zkXfrd-xUnx3bQSXfS9tEvMdfx3TlwOnZ0UmkZcUm0ZdQ29ZMI0QrMBhQ10c3oPMMILcBKCPApULPKp2jww1SJAuI73NRtH1I9wQLgIkNWw8EeOXEUeK3QTAPohViT2LiBLI3jpMSYV1lo74sEUxU7DbA4kjbDxiQAOQQMAZj4OwMlbdVtPAPSDPwDtwW7fiFIk3jkXbaJ4V8JEES6aEBOcromS8g98AmO0gqwMsWjsULi3YKLzP8DELHWWKLjBHlIrfV9RHcPR0UCMZYukKLbzNQYH1GAAjU4JWIJgvzAQj8HoeQAA9TgwZSMCQUjnHAbUKhAABJABhAAdABnAaADsAAcTAscaABEAEsAHt9HGoazCMABbaalsm6o+BW-rFEyCocCQZinEeBx6GFU5MiOk7y3AMpiDoIEbuu7wRDKb53tUGYKA++YZWIPhcgegAxCAmoWdgeBAKHIg4ABHEwOEmo4AE8+CAA);

![image](https://user-images.githubusercontent.com/447240/169887043-fbd6a2e8-d60b-4af2-8617-155cbedb4b54.png)

Note that I also removed 
* the resistor in the front that puts some feedback, as we want to have a clean logic buffer. 
* the connection between the red and green LED
* the non standard values. Now it's only using 1kΩ & 1MΩ.

Note that the CD4069UB has some input clamping diodes, which are an essential part of this circuit, the relevant ones are represented in the box. If you remove them, you'll notice that it is much more erratic. I guess the CD4001 has the same ones.

**Comment by tardate** [comment]
Thanks @steveschnepp , good suggestion. I've added a demo in https://github.com/tardate/LittleArduinoProjects/tree/master/Electronics101/CD4069/LogicProbe

NB: I had to replace the first diode with a link to allow the oscillator to run.
