### ISSUE TITLE
[CD4069/LogicProbe] Another Improvement and some explanations

### ISSUE THREAD

**Issue by steveschnepp** [tardate/LittleArduinoProjects#30]
It's me again, sorry 😉 

I did not understand at first why you had to remove the input diode to make it work. That was not satisfactory. Therefore I had to look deeper into the circuit. I discovered quickly that the capacitor is not part of an _oscillator_, but is part of a _high-pass filter_. 
Once that is known, we can simply keep the high-pass filter and only buffer it with 2 NOT gates in input & output.

Note that, as we don't invert the filter anymore, we have to connect the filter resistor to the ground, and fully remove the feedback circuit. Note that here also, the input clamping diodes of the output NOT gate are helping the high-pass filter signal to stabilize. And if you really look into slow oscillation, you can see that the filter is actually a "monostable rising edge detector" 🤣.

The result is a **much cleaner** [version of the circuit](https://www.falstad.com/circuit/circuitjs.html?ctz=CQAgjCAMB0l5AWAnC1b0DYQHZobEtgBwCsGJ2ATIZBSAliSCZMwKYC0YYAUAO7NsWSlRAZKCECMpQeYcWIngkM8ZOlSQAEzYAzAIYBXADYAXDsbZbwUWzEi95qpRrUgAzJVYydBk+ctrVghWe14AJ0VJAmdoyiJbMHgeSLdPVjSiSWDkgTcwePpPcELIHgBzKI8sqoQ4Ox4AJSKZAoSEYqJQ2zrmOyhoEib6JGFRBAQEjW96KUG5plDBngBjEC7vUSyp0WDYeAPDuDBObBAuaCR3FGJsKiSC92wQ-fgI9cnqyW2pXfAjuQKJK9ShKYGbGQ+PRGMwWKw2EIDBz8KptHBeEoJMoCKjBQo-NHY5gYbxkYkQ2QCMgU6lSIhYlG0jQUMYyIkkApSXocyG7Rmc5mc9yISnMAXjUa-NnDJlKWkxfrc-owIaVWnpckedxYUI8XRiyHcklc1judzgeb2Sh6g0eEXqkXFMCW2DW-XYbV2yTESTC32tF2QN04T0SVg+k1ai2LV0VHA1DURs062TNCOg701BXdJXdFUoj2snAi6YF0O9QtS0Xprb1Us4moadP06uNsk16X6pATL0gFAyP0eAMxoM27vqXr9yNm6NI62VKcaxee3XNKcZvsqZRsnqsRZ2ZYCcdVoiS+t9nsaY+DonHsMX9R8o9bjRJSA7aXP3kydct28vsl1yfEMi0rG8Un+Xo0XBKQlByOA41PLANSQrUUzKaxUJQs9RChPwzBRVCNB+UtMJwmQiJcbRoX8YZKO+SVs13Po82WAAjdYiAHEgmAeXiiB1FE3CbEtgIJQoYMJFE3w-SCKTKSofncGofjqPMeA454kA8EhzS6aIajKDjkASdxdOYIhzTAQyeAAe3ACB5A8EpqD3JFjlsPTbFMuyHPAFMwA6J5zXsDzQs8IgwG1SgMFPLp4gQIRbFaCB3B4ZT1hAAAxVLkvqLhsvCNgAEdDDYAA7FYAE8eCAA), which I think is the minimal one now.

![image](https://user-images.githubusercontent.com/447240/170083330-e47af010-a3ce-46c2-8e73-ce049101e361.png)

**Comment by steveschnepp** [comment]
And, totally ironically, I just discovered that is even an already "well known circuit" : the [Leading Edge Detector](https://www.falstad.com/circuit/e-leadingedge.html). 🤦

**Comment by tardate** [comment]
good stuff @steveschnepp  I'll try that...

**Comment by tardate** [comment]
thanks @steveschnepp I finally got around to updating the project notes!

**Comment by steveschnepp** [comment]
Great job 👍

Btw, I'm wondering... You mentioned CD4069UBC, which is *Unbuffered*, but in the picture there is a CD4069BE, which should be *Buffered*.

So the various information out there is contradictory at best. Some saying exactly that difference and some saying that the CD4069 does *not* exists in a buffered version.

I'm wondering how to test if it is buffered or not 🤔

**Comment by tardate** [comment]
good question.

It does seem the 4069 was only ever singly buffered / single-stage design (according the CMOS cookbook).

It does make one wonder what this apparently "TI CD4069BE" chip is I have in my parts box;-)
I can't find any reference to a "CD4069BE" from TI or in a bunch of old data books I found on archive.org.

I should put it under test for the variable output impedance one would expect with an unbuffered design.

**Comment by steveschnepp** [comment]
Indeed. I am wondering about a test that would work to differentiate buffered from unbuffered.

**Comment by steveschnepp** [comment]
Just asked on [EE.SE](https://electronics.stackexchange.com/questions/635840/how-to-test-if-an-ic-output-is-buffered)

**Comment by steveschnepp** [comment]
And the answer is to simply do a X/Y transfer test. It would be interesting to compare:

* 1 CD4069UBE
* 3 CD4069UBE in series 
* 1 CD4001BE with its inputs tied
