### ISSUE TITLE
MilliVoltmeterDIY

### ISSUE THREAD

**Issue by alex1sh** [tardate/LittleArduinoProjects#8]
Hi Paul,

Excellent work on the MilliVoltmeter!
Do you mind me asking where you got your project box please?
It looks very nice.

Thanks
Alex

**Comment by tardate** [comment]
Thanks for the nice comments @alex1sh!

I picked up the instrument box while browsing at Sim Lim Tower (Singapore). I **think** it is something like this [Future Box FB10](https://www.futurekit.com/product/25661/fb10). When I get back to my workspace (in a few days) I'll check properly and update my notes with dimensions etc at https://github.com/tardate/LittleArduinoProjects/tree/master/Equipment/MilliVoltmeterDIY/CustomBoardAndEnclosure

Cheers,
Paul
