### ISSUE TITLE
No RSS Feed on the blog site itself

### ISSUE THREAD

**Issue by kenfallon** [tardate/LittleArduinoProjects#9]
Great idea all !

Could you perhaps add a RSS/Atom feed to the site https://leap.tardate.com/ so new post appear in readers !

**Comment by tardate** [comment]
hi @kenfallon, thanks for popping by!

Yes, an RSS/Atom feed is good idea. I need to fiddle with how the web site is generated, but should be easy enough (and improve a couple of other aspects I not so satisfied with at the same time). On the list!

**Comment by tardate** [comment]
@kenfallon I've added an atom feed to the site: http://www.feedvalidator.org/check.cgi?url=https%3A%2F%2Fleap.tardate.com
Does this work ok with whatever feed reader you're using?

**Comment by tardate** [comment]
Seems ok so far, so I'll close this for now.
